[2023-07-08 17:27:23,106] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.extraer_data manual__2023-07-08T17:27:14.707211+00:00 [queued]>
[2023-07-08 17:27:23,240] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.extraer_data manual__2023-07-08T17:27:14.707211+00:00 [queued]>
[2023-07-08 17:27:23,242] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-07-08 17:27:23,243] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2023-07-08 17:27:23,245] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-07-08 17:27:23,402] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): extraer_data> on 2023-07-08 17:27:14.707211+00:00
[2023-07-08 17:27:23,417] {standard_task_runner.py:52} INFO - Started process 137 to run task
[2023-07-08 17:27:23,462] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Regions_ETL', 'extraer_data', 'manual__2023-07-08T17:27:14.707211+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Regions.py', '--cfg-path', '/tmp/tmpw0nlach3', '--error-file', '/tmp/tmp4k14vx9l']
[2023-07-08 17:27:23,467] {standard_task_runner.py:77} INFO - Job 8: Subtask extraer_data
[2023-07-08 17:27:23,890] {logging_mixin.py:109} INFO - Running <TaskInstance: Regions_ETL.extraer_data manual__2023-07-08T17:27:14.707211+00:00 [running]> on host ecab4011ad96
[2023-07-08 17:27:24,470] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-07-08 17:27:24,621] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gastonrios32
AIRFLOW_CTX_DAG_ID=Regions_ETL
AIRFLOW_CTX_TASK_ID=extraer_data
AIRFLOW_CTX_EXECUTION_DATE=2023-07-08T17:27:14.707211+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-07-08T17:27:14.707211+00:00
[2023-07-08 17:27:24,625] {logging_mixin.py:109} INFO - Adquiriendo data para la fecha: 2023-07-08 17
[2023-07-08 17:27:26,829] {logging_mixin.py:109} INFO - Success!
[2023-07-08 17:27:27,972] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Regions.py", line 59, in extraer_data
    with open(dag_path+'/raw_data/'+"data_"+str(date.year)+'-'+str(date.month)+'-'+str(date.day)+'-'+str(date.hour)+".json", "w") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/raw_data/data_2023-7-8-17.json'
[2023-07-08 17:27:28,348] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=Regions_ETL, task_id=extraer_data, execution_date=20230708T172714, start_date=20230708T172723, end_date=20230708T172728
[2023-07-08 17:27:28,416] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task extraer_data
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_Regions.py", line 59, in extraer_data
    with open(dag_path+'/raw_data/'+"data_"+str(date.year)+'-'+str(date.month)+'-'+str(date.day)+'-'+str(date.hour)+".json", "w") as json_file:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/raw_data/data_2023-7-8-17.json'
[2023-07-08 17:27:28,722] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-08 17:27:29,041] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
