[2023-07-08 18:30:17,751] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.envio_mail scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-08 18:30:17,839] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: Regions_ETL.envio_mail scheduled__2023-07-07T00:00:00+00:00 [queued]>
[2023-07-08 18:30:17,840] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-07-08 18:30:17,843] {taskinstance.py:1239} INFO - Starting attempt 1 of 6
[2023-07-08 18:30:17,845] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-07-08 18:30:17,937] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): envio_mail> on 2023-07-07 00:00:00+00:00
[2023-07-08 18:30:17,947] {standard_task_runner.py:52} INFO - Started process 262 to run task
[2023-07-08 18:30:17,986] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'Regions_ETL', 'envio_mail', 'scheduled__2023-07-07T00:00:00+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/ETL_Regions.py', '--cfg-path', '/tmp/tmp8u4ohl7x', '--error-file', '/tmp/tmpq_j78hhb']
[2023-07-08 18:30:18,021] {standard_task_runner.py:77} INFO - Job 11: Subtask envio_mail
[2023-07-08 18:30:18,445] {logging_mixin.py:109} INFO - Running <TaskInstance: Regions_ETL.envio_mail scheduled__2023-07-07T00:00:00+00:00 [running]> on host 3c75c5b6d9e6
[2023-07-08 18:30:18,758] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2023-07-08 18:30:19,066] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=gastonrios32
AIRFLOW_CTX_DAG_ID=Regions_ETL
AIRFLOW_CTX_TASK_ID=envio_mail
AIRFLOW_CTX_EXECUTION_DATE=2023-07-07T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-07-07T00:00:00+00:00
[2023-07-08 18:30:19,072] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: enviar_email() takes 0 positional arguments but 1 was given
[2023-07-08 18:30:19,130] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=Regions_ETL, task_id=envio_mail, execution_date=20230707T000000, start_date=20230708T183017, end_date=20230708T183019
[2023-07-08 18:30:19,272] {standard_task_runner.py:92} ERROR - Failed to execute job 11 for task envio_mail
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: enviar_email() takes 0 positional arguments but 1 was given
[2023-07-08 18:30:19,389] {local_task_job.py:154} INFO - Task exited with return code 1
[2023-07-08 18:30:19,623] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
